name: CI/CD Pipeline (Build → Push → Deploy to AKS)


on:
push:
branches: [ 'main' ]


jobs:
build-and-deploy:
runs-on: ubuntu-latest


steps:
- name: Checkout
uses: actions/checkout@v4


- name: Set up QEMU (for cross-building if needed)
uses: docker/setup-qemu-action@v2


- name: Set up Docker Buildx
uses: docker/setup-buildx-action@v2


- name: Log in to Docker Hub
uses: docker/login-action@v2
with:
username: ${{ secrets.DOCKER_USERNAME }}
password: ${{ secrets.DOCKER_PASSWORD }}


- name: Build and push Docker image
run: |
IMAGE=${{ secrets.DOCKER_USERNAME }}/helloapp:${{ github.sha }}
docker build -t $IMAGE .
docker push $IMAGE
env:
DOCKER_BUILDKIT: 1


- name: Azure Login
uses: azure/login@v1
with:
creds: ${{ secrets.AZURE_CREDENTIALS }}


- name: Get AKS credentials
run: |
az aks get-credentials --resource-group ${{ secrets.AZURE_RG }} --name ${{ secrets.AZURE_CLUSTER }} --overwrite-existing


- name: Setup kubectl
uses: azure/setup-kubectl@v3


- name: Deploy to AKS (apply manifests)
run: |
IMAGE=${{ secrets.DOCKER_USERNAME }}/helloapp:${{ github.sha }}
sed -i "s|REPLACE_WITH_IMAGE|$IMAGE|g" k8s/deployment.yaml || true
kubectl apply -f k8s/


- name: Wait for Service External IP
run: |
kubectl wait --for=condition=available --timeout=120s deployment/hello-deployment || true
kubectl get svc hello-service -o wide
